name: Deploy React Portfolio to OCI (systemd)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on OCI server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            /home/ubuntu/deploy_react.sh
            cd /home/ubuntu/portfolio && npm run migrate
